### ISSUE TITLE
does not update TLE SatDump, 1.2.0

### ISSUE THREAD

**Issue by LU9DDB** [SatDump/SatDump.Docs#8]
Since 08/19/2024 the TLE has not been updated in SatDump 1.2.0, how to solve the problem, thanks for any suggestions.
![TLE](https://github.com/user-attachments/assets/4ca27ea1-f73b-4fdc-8f2e-5e81d8ea70c3)

**Comment by RAD750** [comment]
The issue has already been solved, please [download the latest nightly](https://github.com/SatDump/SatDump/releases/tag/nightly) for your operating system.
Also, please don't create issues in the docs repository unless they are related to documentation issues. The correct repository for issues related to the SatDump program itself [is this one](https://github.com/SatDump/SatDump/issues)

Thanks, and enjoy SatDump!

**Comment by LU9DDB** [comment]
Thanks for the advice, I didn't mean to create a problem,

Congratulations on the software, I am very happy to use SatDump..
    El sábado, 31 de agosto de 2024, 03:38:51 a. m. ART, Jacopo ***@***.***> escribió:  
 
 


The issue has already been solved, please download the latest nightly for your operating system.
Also, please don't create issues in the docs repository unless they are related to documentation issues. The correct repository for issues related to the SatDump program itself is this one

Thanks, and enjoy SatDump!
