### ISSUE TITLE
V1.2 dll  re: Win 11, laptop

### ISSUE THREAD

**Issue by orbit6810** [SatDump/SatDump.Docs#9]
vcruntime140.dll

versus

  vcruntime140_1.dll

on my machine 140_1 exists at 
  Sys -> Software Env -> loaded modules

so, why does SatDump show the error screen for 140.dll under their " problems" i may have when trying to run the build ???

What file is V 1.2 build looking for and WHERE IS IT LOOKING - "full path" ???

**Comment by JVital2013** [comment]
It is looking for it in the standard DLL search paths, which includes the normal location of C:\Windows\System32. If these DLLs are missing, you need to re-install the Microsoft Visual C++ Redistributable for 2015-2022 as described in the FAQ. Both vcruntime140.dll and vcruntime140_1.dll are a part of this redistributable.

FYI, we do not really monitor issues here - for a more timely response, [please open issues on the main SatDump issues page](https://github.com/SatDump/SatDump/issues).
